<!DOCTYPE html>
<html>
 <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PLP Alumni Portal</title>
    <link rel="stylesheet" href="style.css" />
 </head>
    <body>
    <nav class="navbar">
    <div class="navdiv">
      <div class="header-left">
        <img src="images/plp-logo.png" alt="PLP Logo" class="logo" />
        <div>
          <h1>Pamantasan Ng Lungsod Ng Pasig</h1>
          <p>Alkalde Jose St. Kapasigan, Pasig City</p>
        </div>
      </div>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Events</a></li>
        <li><a href="alumni-list.php">Alumni List</a></li>
        <li><a href="#">Gallery</a></li>
        <li class="portal-label">PORTAL</li>
      </ul>
     </div>
   </nav>
   <div>
   <form class="search">
      <input type="text" placeholder="Search"/>
      <button><span>&#128269</span></button>
   </form>
   </div>

   <div class="grid">
      <div class="student-info">
         <h3>Student 1</h3>
         <div class="avatar"></div>
      </div>
      <div class="student-info">
         <h3>Student 2</h3>
         <div class="avatar"></div>
      </div>
      <div class="student-info">
         <h3>Student 3</h3>
         <div class="avatar"></div>
      </div>
      <div class="student-info">
         <h3>Student 4</h3>
         <div class="avatar"></div>
      </div>
      <div class="student-info">
         <h3>Student 5</h3>
         <div class="avatar"></div>
      </div>
      <div class="student-info">
         <h3>Student 6</h3>
         <div class="avatar"></div>
      </div>
   </div>

    </body>
</html>